# Настройки базы данных
database_name: "test_db"
user: "admin"
password: "secret_password"

let:
  name: "max_rows"
  value: "5000"

max_rows_per_table: $max_rows$

tables:
  - "12"
  - "orders"
  - "products"
  - $max_rows$