# Конфигурация веб-сервера
server_name: "example.com"
port: "80"
root: "/var/www/html"

let:
  name: "max_connections"
  value: "100"

timeout: $max_connections$

file:
  - "config/nginx.conf"
  - "config/default.conf"